name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_MLOPS}}
    - name: Run ML job
      id: ml_job
#      run: az ml job create --file src/job-cluster.yml -g RG-WSCS -w aml-valerii
      run: az ml job create -f src/job-cluster.yml -g RG-WSCS -w aml-valerii --query name -o tsv
    - name: Run output
      run: echo "Run id is ${{ steps.ml_job.outputs.stdout }}"


