name: Train model

on:
  push:
    branches: [ main ]

jobs:
  dev-job:
    runs-on: ubuntu-latest
    environment:
        name: dev 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: install az ml extension
      run: az extension add -n ml -y
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_MLOPS}}
    - name: set current directory
      run: cd src
    - name: run pipeline
      run: az ml job create --file src/job-cluster.yml -g RG-WSCS -w aml-valerii -s
  
  prod-job:
    needs: dev-job
    runs-on: ubuntu-latest
    environment:
        name: prod 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: install az ml extension
      run: az extension add -n ml -y
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_PROD}}
    - name: set current directory
      run: cd src
    - name: run pipeline
      id: prod-run
      run: run_id=$(az ml job create --file src/job-cluster-prod.yml -g RG-WSCS -w aml-valerii --query name -o tsv) >> $GITHUB_OUTPUT
    - name: register model
      run: az ml model create -n diabetes-data-example -v 1 -p runs:/${{steps.prod-run.outputs.run_id}}/model --type mlflow_model -g RG-WSCS -w aml-valerii